### ISSUE TITLE
ui5-lib configuration does not match with HANA 2 Express 

### ISSUE THREAD

**Issue by kranz** [SAP/com.sap.openSAP.hana5.templates#2]
Having downloaded HANA 2.0 Express Edition from SAP web site, 
the xs MTA for local sapui5 deployment is named XSAC_UI5_FESV2, and the installed version is 1.38.10
This should be reflected in ui5-lib configuration in exercise 4, file 4_1

```
 - name: ui5-lib
   type: configuration 
   parameters:
      ID: com.sap.ui5.dist.sapui5-dist-xsa.XSAC_UI5_FESV2:sapui5_fesv2 # Specifies the the ID of the provider MTA.
      name: sapui5_fesv2
      version: "=1.38.10"     # The version (range) of the provider MTA.

```
